// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-Expense/pkg/api"
	"go-Expense/pkg/api/handlers"
	"go-Expense/pkg/config"
	"go-Expense/pkg/db"
	"go-Expense/pkg/repository"
	"go-Expense/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	client, err := db.ConnectToDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(client)
	userUsecase := usecase.NewUserUsecase(userRepo)
	userHandler := handlers.NewUserHandler(userUsecase)
	server := api.NewServer(userHandler)
	return server, nil
}
